### ISSUE TITLE
"Cube2.py" should be renamed as "cube.py"

### ISSUE THREAD

**Issue by jeddchoi** [Han-SeungJun/Cube#2]
According to PEP8, file name should be lowercases with underscores.
I think, you should follow this convention although you do not want to  follow other naming conventions of variables, function names, etc.

The reason is in link below.

https://stackoverflow.com/a/52767753

**Comment by Han-SeungJun** [comment]
I agree to your comment.
I will renamed from "Cube2.py" to "cube.py".

**Comment by jeddchoi** [comment]
Great to see your reaction! 🙂 As this issue is resolved, I will close this thread.
