### ISSUE TITLE
Project documentation suggestions..

### ISSUE THREAD

**Issue by jeddchoi** [Han-SeungJun/Cube#3]
You had better...

1. Write "Readme.md" file in **English** so that other foreigners could understand this project. (Use translators 😉)
2. Use 'docstring' in python code for documentation so that you can generate API Docs(in format reStructuredText or Markdown) easily by python documentation tools such as Sphinx, doxygen, MkDocs, etc. You will want to compare these tools.

I will add more suggestions If I come up with a better idea.

**Comment by Han-SeungJun** [comment]
i think too a few days ago. I accept your comment and I will rewrite the markdown file. thank you for your comment.
God bless you.

**Comment by Han-SeungJun** [comment]
'docstring' is a good function! Thanks for your recommendation.
