### ISSUE TITLE
Raed.me in main branch

### ISSUE THREAD

**Issue by jeddchoi** [Han-SeungJun/Cube#6]
1. Typo in file name

It should be named as `README.md` so that Github can recognize it.

2. Why don't you use markdown headings?

You are using HTML tags such as `<h1>` although you can do same thing easily with `#`.
You can utilize `README.md` template file in [this link](https://github.com/dbader/readme-template/blob/master/README.md). (Use `RAW` button to view source file.)

Using a template will make it more plausible.🙂

If you want to learn more markdown grammar quickly, see [this link](https://github.com/tchapi/markdown-cheatsheet)

**Comment by Han-SeungJun** [comment]
Thank you for your suggestion!
I will learn more about markdown grammar.
